name: Autograding Tests
on:
  - push
  - workflow_dispatch

permissions:
  actions: read
  contents: read

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-json-report

      - name: Run tests for exercise1
        id: exercise1
        run: |
          # Set default result (failure)
          echo '{"version":3,"status":"fail","tests":[{"name":"test","status":"fail","test_code":"","task_id":0,"filename":"tests/test_get_sum.py","line_no":4,"duration":1,"score":0}],"max_score":5}' | base64 -w 0 > exercise1_encoded.txt
          echo "EXERCISE1_RESULT=$(cat exercise1_encoded.txt)" >> $GITHUB_ENV

          # Run pytest
          pytest -q --json-report --json-report-file=exercise1.json tests/test_get_sum.py
          TEST_RESULT=$?

          # Overwrite result on success
          if [ $TEST_RESULT -eq 0 ]; then
            echo '{"version":3,"status":"pass","tests":[{"name":"test","status":"pass","test_code":"","task_id":0,"filename":"tests/test_get_sum.py","line_no":4,"duration":1,"score":5}],"max_score":5}' | base64 -w 0 > exercise1_encoded.txt
            echo "EXERCISE1_RESULT=$(cat exercise1_encoded.txt)" >> $GITHUB_ENV
          fi
        continue-on-error: true

      - name: Run tests for exercise2
        id: exercise2
        run: |
          # Set default result (failure)
          echo '{"version":3,"status":"fail","tests":[{"name":"test","status":"fail","test_code":"","task_id":0,"filename":"tests/test_greet.py","line_no":4,"duration":1,"score":0}],"max_score":20}' | base64 -w 0 > exercise2_encoded.txt
          echo "EXERCISE2_RESULT=$(cat exercise2_encoded.txt)" >> $GITHUB_ENV

          # Run pytest
          pytest -q --json-report --json-report-file=exercise2.json tests/test_greet.py
          TEST_RESULT=$?

          # Overwrite result on success
          if [ $TEST_RESULT -eq 0 ]; then
            echo '{"version":3,"status":"pass","tests":[{"name":"test","status":"pass","test_code":"","task_id":0,"filename":"tests/test_greet.py","line_no":4,"duration":1,"score":20}],"max_score":20}' | base64 -w 0 > exercise2_encoded.txt
            echo "EXERCISE2_RESULT=$(cat exercise2_encoded.txt)" >> $GITHUB_ENV
          fi
        continue-on-error: true

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: exercise1,exercise2
        env:
          EXERCISE1_RESULT: ${{ env.EXERCISE1_RESULT }}
          EXERCISE2_RESULT: ${{ env.EXERCISE2_RESULT }}
