name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Run tests for Exercise 1
      - name: Run tests for Exercise 1
        id: exercise1
        run: pytest -q tests/test_get_sum.py || echo "Test failed"
        continue-on-error: true

      # Run tests for Exercise 2
      - name: Run tests for Exercise 2
        id: exercise2
        run: pytest -q tests/test_greet.py || echo "Test failed"
        continue-on-error: true

      # Debug step to output results
      - name: Debug Results
        run: |
          echo "Exercise 1 results: ${{ steps.exercise1.outcome }}"
          echo "Exercise 2 results: ${{ steps.exercise2.outcome }}"

      # Autograding Reporter
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: exercise1,exercise2
        env:
          EXERCISE1_RESULTS: ${{ steps.exercise1.outcome }}
          EXERCISE2_RESULTS: ${{ steps.exercise2.outcome }}
