name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Run tests for Exercise 1
      - name: Run tests for Exercise 1
        id: exercise1
        run: pytest -q tests/test_get_sum.py
        continue-on-error: true

      # Run tests for Exercise 2
      - name: Run tests for Exercise 2
        id: exercise2
        run: pytest -q tests/test_greet.py
        continue-on-error: true

      # Autograding Reporter
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: |
            EXERCISE1_RESULTS: ${{ steps.exercise1.outcome }}
            EXERCISE2_RESULTS: ${{ steps.exercise2.outcome }}
          points: |
            EXERCISE1_RESULTS: 5
            EXERCISE2_RESULTS: 15
